package com.karim.foodrun.orders

/** Arabic labels transcribed and normalized for the built-in restaurant menus. */
internal object ArabicMenuNames {
    private val categories = mapOf(
        "The Dish" to "الأطباق", "Sandwiches" to "السندويشات", "Drinks" to "المشروبات", "Manakish" to "المناقيش",
    )
    private val variants = mapOf(
        "Small" to "صغير", "Medium" to "وسط", "Large" to "كبير", "Regular" to "عادي",
        "Samoon" to "صمون", "Shrak" to "شراك", "Tannour" to "تنور", "Kaak" to "كعك", "Lebanese" to "لبناني", "Saj" to "صاج",
    )
    private val items = mapOf(
        "Beans With Corn Oil Dish" to "طبق فول بزيت الذرة",
        "Beans With Oil (Spicy And Olive)" to "فول بالزيت الحار أو زيت الزيتون",
        "Beans With Ghee Dish" to "طبق فول بالسمن",
        "Beans With Sauce Dish" to "طبق فول بالصلصة",
        "Beans With Alexandrian Sauce Dish" to "طبق فول إسكندراني",
        "Beans With Eggs Dish" to "طبق فول بالبيض",
        "Mixed Dish" to "طبق مشكل",
        "Sultan's Service" to "سرفيس سلطان",
        "Falafel Dish" to "طبق طعمية",
        "French Fried Potato Dish" to "طبق بطاطس مقلية",
        "Mashed Potato Dish" to "طبق بطاطس مهروسة",
        "Mashed Egg Dish" to "طبق بطاطس مهروسة بالبيض",
        "Mussaka Dish" to "طبق مسقعة",
        "Fried Eggplant Dish With Flour" to "طبق باذنجان مقلي بالدقيق",
        "Stuffed Falafel Dish" to "طبق طعمية محشية",
        "Cheese And Tomato Dish" to "طبق جبنة وطماطم",
        "Boiled Egg Dish" to "طبق بيض مسلوق",
        "Fried Egg Dish" to "طبق بيض مقلي",
        "Fried Egg With Cheese Dish" to "طبق بيض مقلي بالجبنة",
        "Eggs With Pastrami Dish" to "طبق بيض بالبسطرمة",
        "Eggs With Sausage Dish" to "طبق بيض بالسجق",
        "Shakshouka Dish" to "طبق شكشوكة",
        "Alexandrian Liver Dish" to "طبق كبدة إسكندراني",
        "Alexandrian Sausage Dish" to "طبق سجق إسكندراني",
        "Stuffed Falafel Ball" to "قرص طعمية محشي",
        "2 Falafel Balls" to "٢ قرص طعمية",
        "Alexandrian Falafel" to "طعمية إسكندراني",
        "Falafel Stuffed With Cheese" to "طعمية محشية بالجبنة",
        "Falafel" to "طعمية",
        "Stuffed Falafel" to "طعمية محشية",
        "Romy Falafel" to "طعمية رومي",
        "Potato Falafel" to "طعمية بالبطاطس",
        "Eggplant Falafel" to "طعمية بالباذنجان",
        "Egg Falafel" to "طعمية بالبيض",
        "Mixed" to "مشكل",
        "Saroukh" to "صاروخ",
        "Beans With Corn Oil" to "فول بزيت الذرة",
        "Beans With Oil (Hot - Olive)" to "فول بالزيت الحار أو زيت الزيتون",
        "Alexandrian Fava Bean" to "فول إسكندراني",
        "Beans With Sausage" to "فول بالسجق",
        "Beans With Sauce" to "فول بالصلصة",
        "Foul Ghee" to "فول بالسمن",
        "Beans With Egg" to "فول بالبيض",
        "Falafel Fava Bean" to "فول بالطعمية",
        "Potato Fries" to "بطاطس مقلية",
        "Romy Potato" to "بطاطس رومي",
        "Mashed Potato" to "بطاطس مهروسة",
        "Romy Mashed Potato" to "بطاطس مهروسة رومي",
        "Mashed Potatoes With Egg" to "بطاطس مهروسة بالبيض",
        "Eggplant" to "باذنجان",
        "Mussaka" to "مسقعة",
        "Cheese And Tomato" to "جبنة وطماطم",
        "Boiled Egg" to "بيض مسلوق",
        "Fried Egg" to "بيض مقلي",
        "Fried Egg And Cheese" to "بيض مقلي بالجبنة",
        "Shakshouka" to "شكشوكة",
        "Egg With Pastrami" to "بيض بالبسطرمة",
        "Egg And Sausage" to "بيض بالسجق",
        "Alexandrian Liver" to "كبدة إسكندراني",
        "Alexandrian Sausage" to "سجق إسكندراني",
        "Loaf Hawawshi" to "رغيف حواوشي",
        "Sausage Hawawshi Loaf" to "رغيف حواوشي سجق",
        "Mozzarella Hawawshi Loaf" to "رغيف حواوشي موزاريلا",
        "Alexandrian Hawawshi" to "حواوشي إسكندراني",
        "Suleimani Tea" to "شاي سليماني",
        "Milk Tea" to "شاي بالحليب",
        "Green Tea" to "شاي أخضر",
        "Turkish Coffee" to "قهوة تركية",
        "Nescafe Black" to "نسكافيه سادة",
        "Nescafe Milk" to "نسكافيه بالحليب",
        "Teapot" to "براد شاي",
        "Soft Drinks" to "مشروبات غازية",
        "Chicken liver and hummus" to "كبدة دجاج وحمص",
        "Chicken liver with egg & onion" to "كبدة دجاج مع البيض والبصل",
        "Lamb liver with hummus" to "كبدة غنم مع الحمص",
        "Kidney sandwich with hummus" to "كلاوي مع الحمص",
        "Plain fried eggs" to "بيض مقلي سادة",
        "Eggs with meat" to "بيض مع اللحمة",
        "Mferakeh egg and potato" to "مفركة بيض وبطاطا",
        "Egg with nabulsi cheese" to "بيض مع جبنة نابلسية",
        "Shakshoka egg and tomato" to "شكشوكة بيض وطماطم",
        "Ajjieh (egg & parsley)" to "عجة بيض وبقدونس",
        "Fried cheese" to "جبنة مقلية",
        "Falafel with hummus and salad" to "فلافل مع حمص وسلطة",
        "Falafel, hummus, vegetables, fried & salad" to "فلافل وحمص وخضار مقلية وسلطة",
        "Mixed vegetables fried" to "خضار مقلية مشكلة",
        "Foul sandwich" to "سندويش فول",
        "Foul, falafel and fried vegetables" to "فول وفلافل وخضار مقلية",
        "Super stuffed falafel" to "فلافل سوبر محشية",
        "Super stuffed falafel with cheese" to "فلافل سوبر محشية بالجبنة",
        "Al Kalha falafel super and qalaya" to "فلافل الكلحة سوبر وقلاية",
        "French fries sandwich" to "سندويش بطاطا مقلية",
        "Spicy potato sandwich" to "سندويش بطاطا حارة",
        "Mutabal (eggplant)" to "متبل باذنجان",
        "Hummus and meat" to "حمص ولحمة",
        "Pieda Mankosha Normal" to "منقوشة بيدا عادي",
        "Pieda Mankosha Mix" to "منقوشة بيدا مشكل",
        "Pizza Margherita" to "بيتزا مارغريتا",
        "Pizza with meat" to "بيتزا باللحمة",
        "Vegetable pizza" to "بيتزا خضار",
        "Musakhan onion and sumac Mankosha" to "منقوشة مسخن بصل وسماق",
        "Lahm with green dough / pomegranate molasses" to "لحمة بعجين خضراء ودبس رمان",
        "Meat and cheese mankosha" to "منقوشة لحمة وجبنة",
        "Akkawi cheese" to "جبنة عكاوي",
        "Kashkawan cheese" to "جبنة قشقوان",
        "Mortadella cheese" to "جبنة مرتديلا",
        "Spinach" to "سبانخ",
        "Spinach cheese" to "سبانخ بالجبنة",
        "Potato" to "بطاطا",
        "Potato with cheese" to "بطاطا بالجبنة",
        "Egg Mankosha" to "منقوشة بيض",
        "Cheese and Egg Mankosha" to "منقوشة جبنة وبيض",
        "Mix cheese" to "أجبان مشكلة",
        "Zaatar" to "زعتر",
        "Cheese with zaatar" to "جبنة مع زعتر",
        "Muhammara" to "محمرة",
        "Muhammara with Kashkawan" to "محمرة مع قشقوان",
        "Labneh" to "لبنة",
        "Labneh with Vegetable" to "لبنة مع خضار",
        "Labneh with Zaatar" to "لبنة مع زعتر",
        "Labneh with Falafel" to "لبنة مع فلافل",
        "Kraft with Honey" to "كرافت مع عسل",
        "Foul with eggs" to "فول بالبيض",
        "Foul with sujiq" to "فول بالسجق",
        "Foul with liver" to "فول بالكبدة",
        "Foul with olive oil / Hot oil" to "فول بزيت الزيتون أو الزيت الحار",
        "Foul with ghee" to "فول بالسمن",
        "Foul muslih" to "فول مصلح",
        "Foul with corn oil" to "فول بزيت الذرة",
        "Foul with pastrami" to "فول بالبسطرمة",
        "Foul with Sauce or Garlic" to "فول بالصلصة أو الثوم",
        "Eggs with pastrami" to "بيض بالبسطرمة",
        "Eggs with sujiq" to "بيض بالسجق",
        "Eggs with cheese" to "بيض بالجبنة",
        "Eggs with romy cheese" to "بيض بالجبنة الرومي",
        "Cheese with tomatoes" to "جبنة بالطماطم",
        "Mashed potatoes" to "بطاطس مهروسة",
        "Mashed potatoes with eggs" to "بطاطس مهروسة بالبيض",
        "French fries" to "بطاطس مقلية",
        "Potato with romy cheese" to "بطاطس بالجبنة الرومي",
        "Shakshuka" to "شكشوكة",
        "Msaqaa" to "مسقعة",
        "Alexandrian liver" to "كبدة إسكندراني",
        "Kofta" to "كفتة",
        "Sujiq" to "سجق",
        "Falafel with romy cheese" to "طعمية بالجبنة الرومي",
        "Egg falafel" to "طعمية بالبيض",
        "Mixed sandwiches" to "سندويشات مشكلة",
        "Mahlah rocket sandwich" to "صاروخ المحلة",
    )

    fun category(value: String) = categories[value].orEmpty()
    fun variant(value: String) = variants[value].orEmpty()
    fun item(value: String) = requireNotNull(items[value]) { "Missing Arabic menu name for $value" }
}
