package com.karim.foodrun.orders

/** Bilingual menu transcribed from the eight Bait Al Waleema menu photos supplied on 20 September 2026. */
internal object BaitAlWaleemaRestaurant {
    private data class SourcePrice(val name: String, val nameAr: String, val amountMinor: Long)
    private data class SourceItem(
        val name: String,
        val nameAr: String,
        val prices: List<SourcePrice>,
        val description: String = "",
        val descriptionAr: String = "",
    )
    private data class SourceCategory(val name: String, val nameAr: String, val items: List<SourceItem>)

    private fun item(
        name: String,
        nameAr: String,
        amountMinor: Long,
        description: String = "",
        descriptionAr: String = "",
    ) = SourceItem(name, nameAr, listOf(SourcePrice("", "", amountMinor)), description, descriptionAr)

    private fun item(
        name: String,
        nameAr: String,
        vararg prices: SourcePrice,
    ) = SourceItem(name, nameAr, prices.toList())

    private fun price(name: String, nameAr: String, amountMinor: Long) = SourcePrice(name, nameAr, amountMinor)
    private fun plate(amountMinor: Long) = price("Plate", "طبق", amountMinor)
    private fun halfKilogram(amountMinor: Long) = price("Half kilogram", "نصف كيلو", amountMinor)
    private fun kilogram(amountMinor: Long) = price("Kilogram", "كيلو", amountMinor)
    private fun category(name: String, nameAr: String, vararg items: SourceItem) = SourceCategory(name, nameAr, items.toList())

    private val source = listOf(
        category("Parties", "الحفلات",
            item("Mun Chicken Biryani", "من دجاج برياني", 22_500),
            item("Mun Mutton Biryani", "من لحم ضأن برياني", 48_000),
            item("Mun Indian Mutton Biryani", "من لحم هندي برياني", 47_000),
            item("Fresh Indian Goat Gozi", "ذبيحة غوزي هندي طازج", 80_000),
            item("Jaziri Goat Gozi", "غوزية ذبيحة جزيري", 120_000),
        ),
        category("Vegetables and Rice", "خضار وأرز",
            item("White Rice", "أرز أبيض", 700),
            item("Vermicelli Rice", "أرز شعرية", 700),
            item("Okra", "بامية", 950),
            item("Potatoes", "بطاطس", 950),
            item("Peas", "بسلة", 950),
            item("Molokhia", "ملوخية", 950),
        ),
        category("Fattah", "الفتة",
            item("Boneless Kaware Fattah", "فتة كوارع مخلية", 4_799),
            item("Lamb Shank Fattah", "فتة موزة ضاني", 4_999),
            item("Egyptian Meat Fattah", "فتة مصري باللحم", 4_399),
            item("Plain Fattah", "فتة سادة", 1_599),
        ),
        category("Soups", "الشوربة",
            item("Meat Soup", "شوربة اللحم", 1_050),
            item("Orzo Soup", "شوربة لسان عصفور", 500),
            item("Plain Kaware Soup", "شوربة كوارع سادة", 650),
            item("Boneless Kaware Soup", "شوربة كوارع مخلية", 1_550),
            item("Chef Kaware Soup", "شوربة كوارع الشيف", 2_400),
            item("Lentil Soup", "شوربة عدس", 500),
            item("Chicken and Mushroom Cream Soup", "شوربة كريمة دجاج ومشروم", 1_550),
        ),
        category("Salads and Appetizers", "السلطات والمقبلات",
            item("Oriental Salad", "سلطة خضراء بلدي", 500),
            item("Pickled Eggplant", "باذنجان مخلل", 500),
            item("Tahini", "طحينة", 525),
            item("Yogurt with Garlic and Mint", "روب بالثوم والنعناع", 525),
            item("Hummus", "حمص", 1_050),
            item("Mutabal", "متبل", 525),
            item("Tabbouleh", "تبولة", 1_050),
            item("Fattoush", "فتوش", 1_050),
            item("Mixed Appetizer Service", "سرفيس مشكل", 1_365),
            item("Shami Kibbeh", "كبيبة شامي", 1_050),
            item("Meat Sambousek", "سمبوسك لحم", 840),
            item("Cheese Sambousek", "سمبوسك جبنة", 840),
            item("Mixed Sambousek", "سمبوسك مشكل", 840),
        ),
        category("Dishes", "الأطباق",
            item("Fesha", "فشة", plate(2_600), kilogram(10_000)),
            item("Spleen", "طحال", plate(2_750), kilogram(10_799)),
            item("Mixed Beef", "سمين مشكل", plate(3_080), kilogram(11_399)),
            item("Mixed Sweetbreads", "حلويات مشكل", plate(3_100), kilogram(11_400)),
            item("Head Meat", "لحمة رأس", plate(3_400), kilogram(12_000)),
            item("Alexandrian Liver", "كبدة إسكندراني", plate(2_750), kilogram(10_750)),
            item("Fried Liver", "كبدة بانيه", plate(3_199), kilogram(11_399)),
            item("Liver and Brain", "كبدة ومخ", plate(3_199), kilogram(11_399)),
            item("Fried Brain", "مخ بانيه", plate(3_199), kilogram(11_399)),
            item("Alexandrian Sausage", "سجق إسكندراني", plate(3_199), kilogram(11_399)),
            item("Seafood Platter", "طبق فواكه البحر", plate(3_399), kilogram(12_099)),
            item("Egyptian Duck", "بط مصري", 4_999, "Half duck with soup, vegetables, and rice.", "نصف بطة مصرية مع شوربة وخضار وأرز."),
            item("Fried Shrimp Platter", "طبق جمبري مقلي", plate(3_400), kilogram(12_600)),
            item("Makhasy Dish", "طبق مخاصي", plate(3_960), kilogram(12_650)),
        ),
        category("Stuffed Dishes", "المحاشي",
            item("Stuffed Vine Leaves", "محشي ورق عنب", 2_199),
            item("Stuffed Cabbage", "ملفوف", 2_199),
            item("Stuffed Zucchini", "كوسة", 2_199),
            item("Stuffed Eggplant", "باذنجان", 2_199),
            item("Stuffed Pepper", "فلفل", 2_199),
            item("Mixed Stuffed Vegetables", "مشكل محاشي", 2_799),
            item("Half Fried Chicken", "نصف دجاجة محمرة", 2_799),
            item("Mumbar", "ممبار", 3_199),
            item("Stuffed Chicken", "دجاجة محشية", 3_699),
            item("Pigeons Stuffed with Rice", "حمام محشي بالأرز", 4_299),
            item("Mixed Stuffed Vegetables with Roasted Meat", "محشي مشكل لحم محمر", 4_099),
            item("Mumbar with Roasted Meat", "ممبار مع لحم محمر", 4_099),
        ),
        category("Grills", "المشاوي",
            item("Egyptian Kofta", "كفتة مصري", plate(3_599), halfKilogram(6_599), kilogram(12_099)),
            item("Egyptian Kebab", "كباب مصري", plate(4_999), halfKilogram(7_999), kilogram(14_499)),
            item("Lamb Chops", "ريش", plate(4_999), halfKilogram(8_499), kilogram(15_999)),
            item("Waleema Mixed Grill", "مشاوي الوليمة", plate(4_399), halfKilogram(7_199), kilogram(13_799)),
            item("Shish Tawook", "شيش طاووق", plate(2_999), halfKilogram(5_699), kilogram(10_499)),
            item("Egyptian Tarb", "طرب مصري", plate(4_999), halfKilogram(8_499), kilogram(15_999)),
            item("Half Boneless Chicken", "نصف دجاج مسحب", 2_999),
            item("Grilled Sausage", "سجق مشوي", plate(3_199), halfKilogram(6_099), kilogram(11_000)),
        ),
        category("Arabic and Gulf Food", "مأكولات عربية وخليجية",
            item("Half Chicken Biryani", "نصف دجاج برياني", 2_199),
            item("Beef Biryani", "لحم برياني", 2_699),
            item("Chicken Mandi", "دجاج مندي", 2_699),
            item("Beef Mandi", "لحم مندي", 4_699),
            item("Mazbi Chicken", "مظبي دجاج", 2_599),
            item("Vegetable Curry", "صالونا خضار", 1_255),
            item("Chicken Majboos", "مكبوس دجاج", 2_599),
            item("Beef Majboos", "مكبوس لحم", 3_099),
            item("Beef Harees - Medium", "هريس لحم وسط", 800),
            item("Beef Harees - Large", "هريس لحم كبير", 1_400),
        ),
        category("Kids Meals", "وجبات الأطفال",
            item("Chicken Strips Meal", "وجبة تشكن استربس", 1_575),
            item("Chicken Nuggets Meal", "وجبة تشكن ناجتس", 1_575),
        ),
        category("Sandwiches", "السندوتشات",
            item("Charcoal Hawawshi Sandwich", "رغيف حواوشي على الفحم", 1_499),
            item("Egyptian Kofta Sandwich", "رغيف كفتة مصري", 1_699),
            item("Egyptian Kebab Sandwich", "رغيف كباب مصري", 1_999),
            item("Egyptian Tarb Sandwich", "رغيف طرب مصري", 1_999),
            item("Shish Tawook Sandwich", "رغيف شيش طاووق", 1_499),
            item("Alexandrian Liver Sandwich", "رغيف كبدة إسكندراني", 1_450),
            item("Egyptian Sausage Sandwich", "رغيف سجق مصري", 1_599),
            item("Grilled Sausage Sandwich", "رغيف سجق مشوي", 1_599),
            item("Fried Liver Sandwich", "رغيف كبدة بانيه", 1_450),
            item("Brain Sandwich", "رغيف مخ", 1_599),
            item("Liver and Brain Sandwich", "رغيف كبدة ومخ", 1_599),
            item("Beef Mix Sandwich", "رغيف سمين", 1_599),
            item("Mixed Sweetbreads Sandwich", "رغيف حلويات مشكل", 1_599),
            item("Head Meat Sandwich", "رغيف لحمة رأس", 1_699),
            item("Shrimp Sandwich", "رغيف جمبري", 1_999),
            item("Fish Fillet Sandwich", "رغيف سمك فيليه", 1_499),
            item("Seafood Sandwich", "رغيف سي فود", 1_999),
        ),
        category("Tagines", "الطواجن",
            item("Okra Tagine with Beef", "طاجن بامية باللحم", 3_999),
            item("Potato Tagine with Beef", "طاجن بطاطس باللحم", 3_999),
            item("Vine Leaves Tagine with Kaware", "طاجن ورق عنب بالكوارع", 4_399),
            item("Orzo Tagine with Beef", "طاجن لسان عصفور باللحم", 4_399),
            item("Orzo Tagine with Akkawi", "طاجن لسان عصفور عكاوي", 4_499),
            item("Beef and Onion Tagine", "طاجن لحم بالبصل", 4_199),
            item("Warqet Beef", "ورقة لحمة", 4_499),
            item("Akkawi Tagine with Onion or Potato", "طاجن عكاوي بالبصل أو بطاطس", 4_499),
            item("Dawood Basha Tagine with Beef", "طاجن داوود باشا باللحم", 3_999),
            item("Molokhia Tagine with Beef", "طاجن ملوخية باللحم", 3_299),
            item("Kaware Tagine with Sauce", "طاجن كوارع بالصلصة", 4_499),
            item("Peas with Beef", "بسلة باللحم", 3_999),
            item("Beans with Beef", "فاصوليا باللحم", 3_999),
        ),
        category("Pasta", "المكرونة",
            item("Béchamel Pasta", "مكرونة بشاميل", 1_799),
            item("Bolognese Pasta", "مكرونة بولونيز", 1_799),
            item("Pasta with Sausage", "مكرونة سجق", 1_999),
            item("Pasta with Liver", "مكرونة كبدة", 1_960),
            item("Seafood Pasta", "مكرونة سي فود", 2_799),
            item("Chicken and Cheese Pasta", "مكرونة دجاج وجبنة", 2_199),
        ),
        category("Family Trays", "الصواني العائلية",
            item("Waleema Friends", "وليمة الصحاب", 15_999,
                "300 g kofta, 6 shish tawook, 2 half chickens, 2 hawawshi, 300 g mumbar, mixed stuffing, 2 vegetables, rice or biryani, salads, and bread.",
                "٣٠٠ جم كفتة، ٦ شيش طاووق، ٢ نصف دجاج، ٢ رغيف حواوشي، ٣٠٠ جم ممبار، محاشي مشكل، نوعان خضار، أرز أو برياني، سلطات وخبز."),
            item("Waleema Grill Family", "وليمة مشاوي فاميلي", 19_599,
                "6 kofta, 9 kebab, 4 lamb chops, 10 shish tawook, 7 tarb, 4 rice, 4 beef soups, salads, and bread.",
                "٦ كفتة، ٩ كباب، ٤ ريش، ١٠ شيش طاووق، ٧ طرب، ٤ أرز، ٤ شوربة لحم، سلطات وخبز."),
            item("Waleema Al Lamma", "وليمة اللمة", 26_099,
                "300 g kofta, 4 shish tawook, 4 stuffed pigeons, 2 half chickens, 2 hawawshi, 400 g mumbar, 6 beef mixed stuffing, rice or biryani, 2 vegetables, salads, and bread.",
                "٣٠٠ جم كفتة، ٤ شيش طاووق، ٤ حمام محشي، ٢ نصف دجاج، ٢ حواوشي، ٤٠٠ جم ممبار، ٦ قطع لحم محمر، أرز أو برياني، نوعان خضار، سلطات وخبز."),
            item("Waleema Bait Al Ezz", "وليمة بيت العز", 36_799,
                "400 g kofta, 6 shish tawook, 6 stuffed pigeons, 2 half chickens, 3 hawawshi, 2 half ducks, mixed stuffing, rice or biryani, 2 vegetables, salads, and bread.",
                "٤٠٠ جم كفتة، ٦ شيش طاووق، ٦ حمام محشي، ٢ نصف دجاج، ٣ حواوشي، ٢ نصف بط، محاشي مشكل، أرز أو برياني، نوعان خضار، سلطات وخبز."),
            item("Waleema Tabtaba", "وليمة طبطبة", 8_499,
                "240 g kofta, 4 shish tawook, half chicken, 1 hawawshi, liver, 2 soups, 1 vegetable, rice, biryani, salads, and bread.",
                "٢٤٠ جم كفتة، ٤ شيش طاووق، نصف دجاج مسحب، رغيف حواوشي، كبدة بانيه، ٢ شوربة، نوع خضار، أرز، برياني، سلطات وخبز."),
            item("Waleema Sultanah", "وليمة سلطنة", 12_500,
                "2 half chicken mandi, 2 half chicken biryani, mandi meat, biryani rice, 2 soups, 1 vegetable, salads, and bread.",
                "٢ نصف دجاج مندي، ٢ نصف دجاج برياني، لحم مندي، أرز برياني، ٢ شوربة، نوع خضار، سلطات وخبز."),
            item("Waleema Chicken Family", "وليمة دجاج فاميلي", 9_999,
                "4 half chickens, 4 rice, 1 potato, 4 soups, salads, and bread.",
                "٤ نصف دجاج، ٤ أرز، بطاطس، ٤ شوربة، سلطات وخبز."),
            item("Waleema Al Hareefa", "وليمة الحريفة", 11_599,
                "300 g sweetbreads, 300 g fat, 300 g head meat, mumbar, 4 plain tripe soups, salads, and bread.",
                "٣٠٠ جم حلويات، ٣٠٠ جم سمين، ٣٠٠ جم لحمة رأس، ممبار، ٤ شوربة كوارع سادة، سلطات وخبز."),
            item("Waleema Al Ensejam", "وليمة الانسجام", 16_999,
                "Grilled meat, rice with nuts, 1 vegetable, 3 soups, salads, and bread.",
                "لاند مشوي، أرز مكبوس بالمكسرات، نوع خضار، ٣ شوربة، سلطات وخبز."),
        ),
    )

    val export: RestaurantExport = run {
        val id = "builtin-bait-al-waleema"
        val categories = source.mapIndexed { index, category ->
            MenuCategory("$id-category-$index", category.name, index, category.nameAr)
        }
        val items = source.flatMapIndexed { categoryIndex, category ->
            category.items.mapIndexed { itemIndex, sourceItem ->
                val itemId = "$id-item-$categoryIndex-$itemIndex"
                val variants = if (sourceItem.prices.size == 1 && sourceItem.prices.single().name.isEmpty()) emptyList() else {
                    sourceItem.prices.mapIndexed { variantIndex, sourcePrice ->
                        MenuVariant("$itemId-variant-$variantIndex", sourcePrice.name, sourcePrice.amountMinor, sourcePrice.nameAr)
                    }
                }
                MenuItem(
                    id = itemId,
                    categoryId = categories[categoryIndex].id,
                    name = sourceItem.name,
                    description = sourceItem.description,
                    basePriceMinor = sourceItem.prices.first().amountMinor,
                    variants = variants,
                    nameAr = sourceItem.nameAr,
                    descriptionAr = sourceItem.descriptionAr,
                )
            }
        }
        RestaurantExport(
            exportId = id,
            restaurant = Restaurant(
                id = id,
                name = "Bait Al Waleema Restaurant",
                nameAr = "مطعم بيت الوليمة",
                currency = "AED",
                contact = RestaurantContact(
                    phoneE164 = "+97165223309",
                    address = "Khalid Lake Trail, Al Majaz Waterfront, Sharjah",
                ),
                pricing = RestaurantPricing(TaxTreatment.INCLUDED),
                notes = "Menu and prices transcribed from the restaurant's eight supplied menu photos on 20 September 2026.",
                menu = Menu(categories = categories, items = items),
            ),
        )
    }
}
