package com.karim.foodrun.orders

// Calling codes and national prefixes: google/libphonenumber PhoneNumberMetadata.xml, 2026-10-07.
// Names: Unicode CLDR via Intl.DisplayNames. No phone-number regexes are copied.
data class CountryDialCode(val region: String, val code: String, val nationalPrefix: String, val name: String, val nameAr: String)
object CountryDialCodes {
    val all = listOf(
        CountryDialCode("AF", "93", "0", "Afghanistan", "أفغانستان"),
        CountryDialCode("AX", "358", "0", "Åland Islands", "جزر آلاند"),
        CountryDialCode("AL", "355", "0", "Albania", "ألبانيا"),
        CountryDialCode("DZ", "213", "0", "Algeria", "الجزائر"),
        CountryDialCode("AS", "1", "1", "American Samoa", "ساموا الأمريكية"),
        CountryDialCode("AD", "376", "", "Andorra", "أندورا"),
        CountryDialCode("AO", "244", "", "Angola", "أنغولا"),
        CountryDialCode("AI", "1", "1", "Anguilla", "أنغويلا"),
        CountryDialCode("AG", "1", "1", "Antigua & Barbuda", "أنتيغوا وبربودا"),
        CountryDialCode("AR", "54", "0", "Argentina", "الأرجنتين"),
        CountryDialCode("AM", "374", "0", "Armenia", "أرمينيا"),
        CountryDialCode("AW", "297", "", "Aruba", "أروبا"),
        CountryDialCode("AC", "247", "", "Ascension Island", "جزيرة أسينشيون"),
        CountryDialCode("AU", "61", "0", "Australia", "أستراليا"),
        CountryDialCode("AT", "43", "0", "Austria", "النمسا"),
        CountryDialCode("AZ", "994", "0", "Azerbaijan", "أذربيجان"),
        CountryDialCode("BS", "1", "1", "Bahamas", "جزر البهاما"),
        CountryDialCode("BH", "973", "", "Bahrain", "البحرين"),
        CountryDialCode("BD", "880", "0", "Bangladesh", "بنغلاديش"),
        CountryDialCode("BB", "1", "1", "Barbados", "بربادوس"),
        CountryDialCode("BY", "375", "8", "Belarus", "بيلاروس"),
        CountryDialCode("BE", "32", "0", "Belgium", "بلجيكا"),
        CountryDialCode("BZ", "501", "", "Belize", "بليز"),
        CountryDialCode("BJ", "229", "", "Benin", "بنين"),
        CountryDialCode("BM", "1", "1", "Bermuda", "برمودا"),
        CountryDialCode("BT", "975", "", "Bhutan", "بوتان"),
        CountryDialCode("BO", "591", "0", "Bolivia", "بوليفيا"),
        CountryDialCode("BA", "387", "0", "Bosnia & Herzegovina", "البوسنة والهرسك"),
        CountryDialCode("BW", "267", "", "Botswana", "بوتسوانا"),
        CountryDialCode("BR", "55", "0", "Brazil", "البرازيل"),
        CountryDialCode("IO", "246", "", "British Indian Ocean Territory", "الإقليم البريطاني في المحيط الهندي"),
        CountryDialCode("VG", "1", "1", "British Virgin Islands", "جزر فيرجن البريطانية"),
        CountryDialCode("BN", "673", "", "Brunei", "بروناي"),
        CountryDialCode("BG", "359", "0", "Bulgaria", "بلغاريا"),
        CountryDialCode("BF", "226", "", "Burkina Faso", "بوركينا فاسو"),
        CountryDialCode("BI", "257", "", "Burundi", "بوروندي"),
        CountryDialCode("KH", "855", "0", "Cambodia", "كمبوديا"),
        CountryDialCode("CM", "237", "", "Cameroon", "الكاميرون"),
        CountryDialCode("CA", "1", "1", "Canada", "كندا"),
        CountryDialCode("CV", "238", "", "Cape Verde", "الرأس الأخضر"),
        CountryDialCode("BQ", "599", "", "Caribbean Netherlands", "هولندا الكاريبية"),
        CountryDialCode("KY", "1", "1", "Cayman Islands", "جزر كايمان"),
        CountryDialCode("CF", "236", "", "Central African Republic", "جمهورية أفريقيا الوسطى"),
        CountryDialCode("TD", "235", "", "Chad", "تشاد"),
        CountryDialCode("CL", "56", "", "Chile", "تشيلي"),
        CountryDialCode("CN", "86", "0", "China", "الصين"),
        CountryDialCode("CX", "61", "0", "Christmas Island", "جزيرة كريسماس"),
        CountryDialCode("CC", "61", "0", "Cocos (Keeling) Islands", "جزر كوكوس (كيلينغ)"),
        CountryDialCode("CO", "57", "0", "Colombia", "كولومبيا"),
        CountryDialCode("KM", "269", "", "Comoros", "جزر القمر"),
        CountryDialCode("CG", "242", "", "Congo - Brazzaville", "الكونغو - برازافيل"),
        CountryDialCode("CD", "243", "0", "Congo - Kinshasa", "الكونغو - كينشاسا"),
        CountryDialCode("CK", "682", "", "Cook Islands", "جزر كوك"),
        CountryDialCode("CR", "506", "", "Costa Rica", "كوستاريكا"),
        CountryDialCode("CI", "225", "", "Côte d’Ivoire", "ساحل العاج"),
        CountryDialCode("HR", "385", "0", "Croatia", "كرواتيا"),
        CountryDialCode("CU", "53", "0", "Cuba", "كوبا"),
        CountryDialCode("CW", "599", "", "Curaçao", "كوراساو"),
        CountryDialCode("CY", "357", "", "Cyprus", "قبرص"),
        CountryDialCode("CZ", "420", "", "Czechia", "التشيك"),
        CountryDialCode("DK", "45", "", "Denmark", "الدانمرك"),
        CountryDialCode("DJ", "253", "", "Djibouti", "جيبوتي"),
        CountryDialCode("DM", "1", "1", "Dominica", "دومينيكا"),
        CountryDialCode("DO", "1", "1", "Dominican Republic", "جمهورية الدومينيكان"),
        CountryDialCode("EC", "593", "0", "Ecuador", "الإكوادور"),
        CountryDialCode("EG", "20", "0", "Egypt", "مصر"),
        CountryDialCode("SV", "503", "", "El Salvador", "السلفادور"),
        CountryDialCode("GQ", "240", "", "Equatorial Guinea", "غينيا الاستوائية"),
        CountryDialCode("ER", "291", "0", "Eritrea", "إريتريا"),
        CountryDialCode("EE", "372", "", "Estonia", "إستونيا"),
        CountryDialCode("SZ", "268", "", "Eswatini", "إسواتيني"),
        CountryDialCode("ET", "251", "0", "Ethiopia", "إثيوبيا"),
        CountryDialCode("FK", "500", "", "Falkland Islands", "جزر فوكلاند"),
        CountryDialCode("FO", "298", "", "Faroe Islands", "جزر فارو"),
        CountryDialCode("FJ", "679", "", "Fiji", "فيجي"),
        CountryDialCode("FI", "358", "0", "Finland", "فنلندا"),
        CountryDialCode("FR", "33", "0", "France", "فرنسا"),
        CountryDialCode("GF", "594", "0", "French Guiana", "غويانا الفرنسية"),
        CountryDialCode("PF", "689", "", "French Polynesia", "بولينيزيا الفرنسية"),
        CountryDialCode("GA", "241", "", "Gabon", "الغابون"),
        CountryDialCode("GM", "220", "", "Gambia", "غامبيا"),
        CountryDialCode("GE", "995", "0", "Georgia", "جورجيا"),
        CountryDialCode("DE", "49", "0", "Germany", "ألمانيا"),
        CountryDialCode("GH", "233", "0", "Ghana", "غانا"),
        CountryDialCode("GI", "350", "", "Gibraltar", "جبل طارق"),
        CountryDialCode("GR", "30", "", "Greece", "اليونان"),
        CountryDialCode("GL", "299", "", "Greenland", "غرينلاند"),
        CountryDialCode("GD", "1", "1", "Grenada", "غرينادا"),
        CountryDialCode("GP", "590", "0", "Guadeloupe", "غوادلوب"),
        CountryDialCode("GU", "1", "1", "Guam", "غوام"),
        CountryDialCode("GT", "502", "", "Guatemala", "غواتيمالا"),
        CountryDialCode("GG", "44", "0", "Guernsey", "غيرنزي"),
        CountryDialCode("GN", "224", "", "Guinea", "غينيا"),
        CountryDialCode("GW", "245", "", "Guinea-Bissau", "غينيا بيساو"),
        CountryDialCode("GY", "592", "", "Guyana", "غيانا"),
        CountryDialCode("HT", "509", "", "Haiti", "هايتي"),
        CountryDialCode("HN", "504", "", "Honduras", "هندوراس"),
        CountryDialCode("HK", "852", "", "Hong Kong SAR China", "هونغ كونغ الصينية (منطقة إدارية خاصة)"),
        CountryDialCode("HU", "36", "06", "Hungary", "هنغاريا"),
        CountryDialCode("IS", "354", "", "Iceland", "آيسلندا"),
        CountryDialCode("IN", "91", "0", "India", "الهند"),
        CountryDialCode("ID", "62", "0", "Indonesia", "إندونيسيا"),
        CountryDialCode("IR", "98", "0", "Iran", "إيران"),
        CountryDialCode("IQ", "964", "0", "Iraq", "العراق"),
        CountryDialCode("IE", "353", "0", "Ireland", "أيرلندا"),
        CountryDialCode("IM", "44", "0", "Isle of Man", "جزيرة مان"),
        CountryDialCode("IL", "972", "0", "Israel", "إسرائيل"),
        CountryDialCode("IT", "39", "", "Italy", "إيطاليا"),
        CountryDialCode("JM", "1", "1", "Jamaica", "جامايكا"),
        CountryDialCode("JP", "81", "0", "Japan", "اليابان"),
        CountryDialCode("JE", "44", "0", "Jersey", "جيرسي"),
        CountryDialCode("JO", "962", "0", "Jordan", "الأردن"),
        CountryDialCode("KZ", "7", "8", "Kazakhstan", "كازاخستان"),
        CountryDialCode("KE", "254", "0", "Kenya", "كينيا"),
        CountryDialCode("KI", "686", "0", "Kiribati", "كيريباتي"),
        CountryDialCode("XK", "383", "0", "Kosovo", "كوسوفو"),
        CountryDialCode("KW", "965", "", "Kuwait", "الكويت"),
        CountryDialCode("KG", "996", "0", "Kyrgyzstan", "قيرغيزستان"),
        CountryDialCode("LA", "856", "0", "Laos", "لاوس"),
        CountryDialCode("LV", "371", "", "Latvia", "لاتفيا"),
        CountryDialCode("LB", "961", "0", "Lebanon", "لبنان"),
        CountryDialCode("LS", "266", "", "Lesotho", "ليسوتو"),
        CountryDialCode("LR", "231", "0", "Liberia", "ليبيريا"),
        CountryDialCode("LY", "218", "0", "Libya", "ليبيا"),
        CountryDialCode("LI", "423", "0", "Liechtenstein", "ليختنشتاين"),
        CountryDialCode("LT", "370", "0", "Lithuania", "ليتوانيا"),
        CountryDialCode("LU", "352", "", "Luxembourg", "لوكسمبورغ"),
        CountryDialCode("MO", "853", "", "Macao SAR China", "منطقة ماكاو الإدارية الخاصة"),
        CountryDialCode("MG", "261", "0", "Madagascar", "مدغشقر"),
        CountryDialCode("MW", "265", "0", "Malawi", "ملاوي"),
        CountryDialCode("MY", "60", "0", "Malaysia", "ماليزيا"),
        CountryDialCode("MV", "960", "", "Maldives", "جزر المالديف"),
        CountryDialCode("ML", "223", "", "Mali", "مالي"),
        CountryDialCode("MT", "356", "", "Malta", "مالطا"),
        CountryDialCode("MH", "692", "1", "Marshall Islands", "جزر مارشال"),
        CountryDialCode("MQ", "596", "0", "Martinique", "جزر المارتينيك"),
        CountryDialCode("MR", "222", "", "Mauritania", "موريتانيا"),
        CountryDialCode("MU", "230", "", "Mauritius", "موريشيوس"),
        CountryDialCode("YT", "262", "0", "Mayotte", "مايوت"),
        CountryDialCode("MX", "52", "", "Mexico", "المكسيك"),
        CountryDialCode("FM", "691", "", "Micronesia", "ميكرونيزيا"),
        CountryDialCode("MD", "373", "0", "Moldova", "مولدوفا"),
        CountryDialCode("MC", "377", "0", "Monaco", "موناكو"),
        CountryDialCode("MN", "976", "0", "Mongolia", "منغوليا"),
        CountryDialCode("ME", "382", "0", "Montenegro", "الجبل الأسود"),
        CountryDialCode("MS", "1", "1", "Montserrat", "مونتسرات"),
        CountryDialCode("MA", "212", "0", "Morocco", "المغرب"),
        CountryDialCode("MZ", "258", "", "Mozambique", "موزمبيق"),
        CountryDialCode("MM", "95", "0", "Myanmar (Burma)", "ميانمار (بورما)"),
        CountryDialCode("NA", "264", "0", "Namibia", "ناميبيا"),
        CountryDialCode("NR", "674", "", "Nauru", "ناورو"),
        CountryDialCode("NP", "977", "0", "Nepal", "نيبال"),
        CountryDialCode("NL", "31", "0", "Netherlands", "هولندا"),
        CountryDialCode("NC", "687", "", "New Caledonia", "كاليدونيا الجديدة"),
        CountryDialCode("NZ", "64", "0", "New Zealand", "نيوزيلندا"),
        CountryDialCode("NI", "505", "", "Nicaragua", "نيكاراغوا"),
        CountryDialCode("NE", "227", "", "Niger", "النيجر"),
        CountryDialCode("NG", "234", "0", "Nigeria", "نيجيريا"),
        CountryDialCode("NU", "683", "", "Niue", "نيوي"),
        CountryDialCode("NF", "672", "", "Norfolk Island", "جزيرة نورفولك"),
        CountryDialCode("KP", "850", "0", "North Korea", "كوريا الشمالية"),
        CountryDialCode("MK", "389", "0", "North Macedonia", "مقدونيا الشمالية"),
        CountryDialCode("MP", "1", "1", "Northern Mariana Islands", "جزر ماريانا الشمالية"),
        CountryDialCode("NO", "47", "", "Norway", "النرويج"),
        CountryDialCode("OM", "968", "", "Oman", "عُمان"),
        CountryDialCode("PK", "92", "0", "Pakistan", "باكستان"),
        CountryDialCode("PW", "680", "", "Palau", "بالاو"),
        CountryDialCode("PS", "970", "0", "Palestinian Territories", "الأراضي الفلسطينية"),
        CountryDialCode("PA", "507", "", "Panama", "بنما"),
        CountryDialCode("PG", "675", "", "Papua New Guinea", "بابوا غينيا الجديدة"),
        CountryDialCode("PY", "595", "0", "Paraguay", "باراغواي"),
        CountryDialCode("PE", "51", "0", "Peru", "بيرو"),
        CountryDialCode("PH", "63", "0", "Philippines", "الفلبين"),
        CountryDialCode("PL", "48", "", "Poland", "بولندا"),
        CountryDialCode("PT", "351", "", "Portugal", "البرتغال"),
        CountryDialCode("PR", "1", "1", "Puerto Rico", "بورتوريكو"),
        CountryDialCode("QA", "974", "", "Qatar", "قطر"),
        CountryDialCode("RE", "262", "0", "Réunion", "روينيون"),
        CountryDialCode("RO", "40", "0", "Romania", "رومانيا"),
        CountryDialCode("RU", "7", "8", "Russia", "روسيا"),
        CountryDialCode("RW", "250", "0", "Rwanda", "رواندا"),
        CountryDialCode("WS", "685", "", "Samoa", "ساموا"),
        CountryDialCode("SM", "378", "", "San Marino", "سان مارينو"),
        CountryDialCode("ST", "239", "", "São Tomé & Príncipe", "ساو تومي وبرينسيبي"),
        CountryDialCode("SA", "966", "0", "Saudi Arabia", "المملكة العربية السعودية"),
        CountryDialCode("SN", "221", "", "Senegal", "السنغال"),
        CountryDialCode("RS", "381", "0", "Serbia", "صربيا"),
        CountryDialCode("SC", "248", "", "Seychelles", "سيشل"),
        CountryDialCode("SL", "232", "0", "Sierra Leone", "سيراليون"),
        CountryDialCode("SG", "65", "", "Singapore", "سنغافورة"),
        CountryDialCode("SX", "1", "1", "Sint Maarten", "سانت مارتن"),
        CountryDialCode("SK", "421", "0", "Slovakia", "سلوفاكيا"),
        CountryDialCode("SI", "386", "0", "Slovenia", "سلوفينيا"),
        CountryDialCode("SB", "677", "", "Solomon Islands", "جزر سليمان"),
        CountryDialCode("SO", "252", "0", "Somalia", "الصومال"),
        CountryDialCode("ZA", "27", "0", "South Africa", "جنوب أفريقيا"),
        CountryDialCode("KR", "82", "0", "South Korea", "كوريا الجنوبية"),
        CountryDialCode("SS", "211", "0", "South Sudan", "جنوب السودان"),
        CountryDialCode("ES", "34", "", "Spain", "إسبانيا"),
        CountryDialCode("LK", "94", "0", "Sri Lanka", "سريلانكا"),
        CountryDialCode("BL", "590", "0", "St. Barthélemy", "سان بارتليمي"),
        CountryDialCode("SH", "290", "", "St. Helena", "سانت هيلينا"),
        CountryDialCode("KN", "1", "1", "St. Kitts & Nevis", "سانت كيتس ونيفيس"),
        CountryDialCode("LC", "1", "1", "St. Lucia", "سانت لوسيا"),
        CountryDialCode("MF", "590", "0", "St. Martin", "سان مارتن"),
        CountryDialCode("PM", "508", "0", "St. Pierre & Miquelon", "سان بيير ومكويلون"),
        CountryDialCode("VC", "1", "1", "St. Vincent & Grenadines", "سانت فنسنت وجزر غرينادين"),
        CountryDialCode("SD", "249", "0", "Sudan", "السودان"),
        CountryDialCode("SR", "597", "", "Suriname", "سورينام"),
        CountryDialCode("SJ", "47", "", "Svalbard & Jan Mayen", "سفالبارد وجان ماين"),
        CountryDialCode("SE", "46", "0", "Sweden", "السويد"),
        CountryDialCode("CH", "41", "0", "Switzerland", "سويسرا"),
        CountryDialCode("SY", "963", "0", "Syria", "سوريا"),
        CountryDialCode("TW", "886", "0", "Taiwan", "تايوان"),
        CountryDialCode("TJ", "992", "", "Tajikistan", "طاجيكستان"),
        CountryDialCode("TZ", "255", "0", "Tanzania", "تنزانيا"),
        CountryDialCode("TH", "66", "0", "Thailand", "تايلاند"),
        CountryDialCode("TL", "670", "", "Timor-Leste", "تيمور - ليشتي"),
        CountryDialCode("TG", "228", "", "Togo", "توغو"),
        CountryDialCode("TK", "690", "", "Tokelau", "توكيلاو"),
        CountryDialCode("TO", "676", "", "Tonga", "تونغا"),
        CountryDialCode("TT", "1", "1", "Trinidad & Tobago", "ترينيداد وتوباغو"),
        CountryDialCode("TA", "290", "", "Tristan da Cunha", "تريستان دا كونا"),
        CountryDialCode("TN", "216", "", "Tunisia", "تونس"),
        CountryDialCode("TR", "90", "0", "Türkiye", "تركيا"),
        CountryDialCode("TM", "993", "8", "Turkmenistan", "تركمانستان"),
        CountryDialCode("TC", "1", "1", "Turks & Caicos Islands", "جزر توركس وكايكوس"),
        CountryDialCode("TV", "688", "", "Tuvalu", "توفالو"),
        CountryDialCode("VI", "1", "1", "U.S. Virgin Islands", "جزر فيرجن الأمريكية"),
        CountryDialCode("UG", "256", "0", "Uganda", "أوغندا"),
        CountryDialCode("UA", "380", "0", "Ukraine", "أوكرانيا"),
        CountryDialCode("AE", "971", "0", "United Arab Emirates", "الإمارات العربية المتحدة"),
        CountryDialCode("GB", "44", "0", "United Kingdom", "المملكة المتحدة"),
        CountryDialCode("US", "1", "1", "United States", "الولايات المتحدة"),
        CountryDialCode("UY", "598", "0", "Uruguay", "أورغواي"),
        CountryDialCode("UZ", "998", "", "Uzbekistan", "أوزبكستان"),
        CountryDialCode("VU", "678", "", "Vanuatu", "فانواتو"),
        CountryDialCode("VA", "39", "", "Vatican City", "الفاتيكان"),
        CountryDialCode("VE", "58", "0", "Venezuela", "فنزويلا"),
        CountryDialCode("VN", "84", "0", "Vietnam", "فيتنام"),
        CountryDialCode("WF", "681", "", "Wallis & Futuna", "جزر والس وفوتونا"),
        CountryDialCode("EH", "212", "0", "Western Sahara", "الصحراء الغربية"),
        CountryDialCode("YE", "967", "0", "Yemen", "اليمن"),
        CountryDialCode("ZM", "260", "0", "Zambia", "زامبيا"),
        CountryDialCode("ZW", "263", "0", "Zimbabwe", "زيمبابوي"),
    )
    fun country(region: String) = all.firstOrNull { it.region == region } ?: all.first { it.region == "AE" }
    fun ascii(value: String): String = value.map { char -> when (char) {
        in '٠'..'٩' -> '0' + (char - '٠')
        in '۰'..'۹' -> '0' + (char - '۰')
        else -> char
    } }.joinToString("")
    fun split(value: String, defaultRegion: String = "AE"): Pair<String, String> {
        val raw = ascii(value).trim()
        val digits = raw.filter { it in '0'..'9' }
        val international = raw.startsWith("+") || raw.startsWith("00")
        val full = if (raw.startsWith("00")) digits.drop(2) else digits
        val preferred = country(defaultRegion)
        if (international) {
            val match = if (full.startsWith(preferred.code)) preferred else all.sortedByDescending { it.code.length }.firstOrNull { full.startsWith(it.code) }
            if (match != null) return match.region to full.drop(match.code.length)
        }
        if (full.startsWith(preferred.code) && full.length >= 11) return preferred.region to full.drop(preferred.code.length)
        return preferred.region to raw
    }
    fun combine(region: String, value: String): String {
        val raw = ascii(value).trim()
        if (raw.isEmpty()) return ""
        if (raw.startsWith("+") || raw.startsWith("00")) return InternationalPhone.normalize(raw)
        val selected = country(region)
        var local = raw.filter { it in '0'..'9' }
        if (local.startsWith(selected.code) && local.length >= 11) local = local.drop(selected.code.length)
        else if (selected.nationalPrefix.isNotEmpty() && local.startsWith(selected.nationalPrefix)) local = local.drop(selected.nationalPrefix.length)
        return InternationalPhone.normalize("+" + selected.code + local)
    }
}
